version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "nextjs-lambda-stack"
s3_prefix = "nextjs-lambda-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"